### ISSUE TITLE
Build up the tree structure for this project.

### ISSUE THREAD

**Issue by KarryRen** [Tennine2077/DIS-SAM#1]
### Excelent work !

If you can build up the tree structure for this project, we can realize the work more simple !

**Comment by Tennine2077** [comment]
After the paper is accepted, we will consider updating the readme based on your suggestions! Currently, you can directly construct the entire framework based on SAM and IS-Net, or perform one-click training according to the Readme. Thank you very much!

**Comment by KarryRen** [comment]
Good, when will you paper be accepted ?

**Comment by Tennine2077** [comment]
We also wanna know...

**Comment by KarryRen** [comment]
OK, be patient. You will get it !
